SELECT
    NOW();

SHOW search_path;

-- Create sequences first
CREATE SEQUENCE sos_reasons_id_seq;
CREATE SEQUENCE service_kilometers_id_seq;
CREATE SEQUENCE cancel_reasons_id_seq;
CREATE SEQUENCE dealer_slots_id_seq;

CREATE TABLE active_service_booking
(
    vinno TEXT NOT NULL,
    bookingtime TIMESTAMPTZ NOT NULL,
    slot TEXT,
    requestid UUID NOT NULL,
    appointmentid INTEGER,
    dmsbookingid TEXT,
    ronumber TEXT,
    servicestatus TEXT NOT NULL,
    dealermeta JSONB,
    bookingmeta JSONB,
    createdby UUID,
    createdat TIMESTAMPTZ,
    PRIMARY KEY (vinno),
    UNIQUE (requestid),
    -- UNIQUE (ronumber),
    -- UNIQUE (dmsbookingid),
    -- UNIQUE (appointmentid),
    FOREIGN KEY (vinno) REFERENCES prodfmscoresch.vehicle (vinno),
    FOREIGN KEY (createdby) REFERENCES prodfmscoresch.users (userid)
);



CREATE TABLE service_booking_log
(
    vinno TEXT NOT NULL,
    requestid UUID NOT NULL,
    updatedat TIMESTAMPTZ NOT NULL,
    updatedby UUID NOT NULL,
    servicestatus TEXT NOT NULL,
    statusmeta JSONB,
    PRIMARY KEY (vinno, requestid, updatedat),
    FOREIGN KEY (vinno) REFERENCES prodfmscoresch.vehicle (vinno),
    FOREIGN KEY (updatedby) REFERENCES prodfmscoresch.users (userid)
);

CREATE INDEX idx_service_booking_log_requestid ON service_booking_log (requestid);




CREATE TABLE service_done_history (
    vinno TEXT,
    bookingtime TIMESTAMPTZ,
    requestid UUID,
    dmsbookingid TEXT NOT NULL,
    ronumber TEXT NOT NULL,
    robillnumber TEXT NOT NULL,
    robilldate TEXT NOT NULL,
    netbillamt INTEGER NOT NULL,
    odometer INTEGER,
    parentcode TEXT NOT NULL,
    locationcode TEXT NOT NULL,
    dealername TEXT,
    dealerlocation TEXT,
    nextduedate TEXT,
    slot TEXT,
    invoice JSONB,
    createdat TIMESTAMPTZ DEFAULT now(),
    createdby UUID,
    PRIMARY KEY (vinno, bookingtime),
    FOREIGN KEY (vinno) REFERENCES prodfmscoresch.vehicle (vinno),
    FOREIGN KEY (createdby) REFERENCES prodfmscoresch.users (userid),
    UNIQUE (requestid),
    -- UNIQUE (ronumber),
    -- UNIQUE (dmsbookingid)
);


CREATE TABLE account_booking_history (
    accountid UUID NOT NULL,
    fleetid UUID NOT NULL,
    vinno TEXT NOT NULL,
    bookingtime TIMESTAMPTZ NOT NULL,
    requestid UUID NOT NULL,
    PRIMARY KEY (accountid, fleetid, vinno, bookingtime, requestid),
    UNIQUE (requestid),
    FOREIGN KEY (vinno) REFERENCES prodfmscoresch.vehicle (vinno),
    FOREIGN KEY (accountid) REFERENCES prodfmscoresch.account (accountid)
);

CREATE INDEX idx_account_booking_history_vinno ON account_booking_history (vinno);



CREATE TABLE adc_service_api_log (
    vinno TEXT NOT NULL,
    requesttime TIMESTAMPTZ DEFAULT now(),
    endpoint TEXT NOT NULL,
    requestpayload JSONB,
    apistatus INTEGER,
    duration BIGINT,
    apiresponse JSONB,
    PRIMARY KEY (vinno, requesttime)
);

CREATE INDEX idx_adc_service_api_log_endpoint ON adc_service_api_log (endpoint);




CREATE TABLE sos_reason (
    id INTEGER NOT NULL DEFAULT nextval('sos_reasons_id_seq'::regclass),
    sosid INTEGER NOT NULL,
    name TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE service_kilometer (
    id INTEGER NOT NULL DEFAULT nextval('service_kilometers_id_seq'::regclass),
    kilometer INTEGER NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE servicesch.onboarding_pending_queue (
    vinno TEXT NOT NULL,
    mobileno TEXT NOT NULL,
    muserid TEXT NOT NULL,
    createdat TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (vinno)
);

CREATE INDEX onboarding_pending_queue_mobileno_idx ON servicesch.onboarding_pending_queue (mobileno);




CREATE TABLE servicesch.onboarding_done (
    vinno TEXT NOT NULL,
    mobileno TEXT NOT NULL,
    muserid TEXT NOT NULL,
    responsebody JSONB DEFAULT '{}'::jsonb,
    createdat TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (vinno, createdat)
);

CREATE INDEX onboarding_done_mobileno_idx ON servicesch.onboarding_done (mobileno);


CREATE TABLE servicesch.onboarding_error (
    vinno TEXT NOT NULL,
    mobileno TEXT NOT NULL,
    muserid TEXT NOT NULL,
    createdat TIMESTAMPTZ DEFAULT now(),
    requestbody JSONB DEFAULT '{}'::jsonb,
    responsebody JSONB DEFAULT '{}'::jsonb,
    PRIMARY KEY (vinno, createdat)
);

CREATE INDEX onboarding_error_mobileno_idx ON servicesch.onboarding_error (mobileno);



CREATE TABLE cancel_reason (
    id INTEGER NOT NULL DEFAULT nextval('cancel_reasons_id_seq'::regclass),
    cancellationid INTEGER,
    name TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (id)
);



CREATE TABLE dealer_slot (
    id INTEGER NOT NULL DEFAULT nextval('dealer_slots_id_seq'::regclass),
    slots TEXT NOT NULL,
    slotoffset INTEGER,
    createdat TIMESTAMPTZ,
    PRIMARY KEY (id)
);


CREATE TABLE servicetype (
    id TEXT NOT NULL,
    description TEXT,
    CONSTRAINT servicetypes_pkey PRIMARY KEY (id)
);









INSERT INTO sos_reason (id, sosid, name, value)
VALUES
  (1, 6, 'Vehicle Not Starting', 'WYH_SOS_VEHIC_NOT_START'),
  (2, 7, 'Battery Discharged', 'WYH_SOS_BTRY_DSCHRG'),
  (3, 8, 'Key Locked/Lost', 'WYH_SOS_KEY_LOCK_LOST'),
  (4, 9, 'Flat Tyre/Stepney Change', 'WYH_SOS_TYR_STP'),
  (6, 11, 'Electrical Problem', 'WYH_SOS_ELECRIC_PRBLM'),
  (7, 12, 'Mechanical Breakdown', 'WYH_SOS_MECH_BRK'),
  (8, 13, 'Accidental Breakdown', 'WYH_SOS_ACD_BREAK');






INSERT INTO service_kilometer (id, kilometer)
VALUES
  (1, 2000),
  (2, 5000),
  (3, 10000),
  (4, 20000),
  (5, 30000),
  (6, 40000),
  (7, 50000),
  (8, 60000),
  (9, 70000),
  (10, 80000),
  (11, 90000),
  (12, 100000),
  (13, 110000),
  (14, 120000),
  (15, 130000),
  (16, 140000),
  (17, 150000),
  (18, 160000),
  (19, 170000),
  (20, 180000),
  (21, 190000),
  (22, 200000),
  (0, 0);




INSERT INTO cancel_reason (id, cancellationid, name, value)
VALUES
  (1, 24, 'Vehicle in use', 'Vehicleinuse'),
  (2, 25, 'I am busy', 'Iambusy'),
  (3, 26, 'Dealer denied service', 'Dealerdeniedservice'),
  (4, 27, 'Dealer denied pickup & drop request', 'Dealerdeniedpickupanddroprequest');




INSERT INTO dealer_slot (id, slots, slotoffset, createdat)
VALUES
  (1, '10:00 AM', 10, NOW());



INSERT INTO servicetype (id, description)
VALUES
    ('repair_lmm_cv', 'Repair'),
    ('accidental_lmm_cv', 'Accidental'),
    ('scheduled_lmm_cv', 'Scheduled');


